version: 2

builds:
  - id: darwin-amd64
    binary: hdls
    goos: [ darwin ]
    goarch: [ amd64 ]
    env:
      - CGO_ENABLED=1
      - CC=o64-clang

  - id: darwin-arm64
    binary: hdls
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang

  - id: linux-amd64
    binary: hdls
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc

  - id: linux-arm64
    binary: hdls
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc

  - id: windows-amd64
    binary: hdls
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc

archives:
  - id: release-archive
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
      - windows-amd64
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

brews:
  - repository:
      owner: quantonganh
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/quantonganh/hdls
    description: >-
      A simple language server for HDL (nand2tetris)
    license: MIT
